In [1]:
import torch
# print(torch.__version__)

"""
creating tensors
"""
# seiries data or 1-D tensor
X1 = torch.tensor([1,2,3,4,5])
print(X1)




tensor([1, 2, 3, 4, 5])


In [2]:

# 2-D tensor

X2 = torch.tensor([[1,2],
                  [3,4]])
print(X2)

tensor([[1, 2],
        [3, 4]])


In [3]:
# for initial values of tensor we can use torch.zeros, torch.ones, torch.rand

X3 = torch.zeros(3,2)
print(X3)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
# for initial values of tensor we can use torch.zeros, torch.ones, torch.rand

X4 = torch.ones(3,2)
print(X4)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [5]:
# for initial values of tensor we can use torch.zeros, torch.ones, torch.rand

X5 = torch.rand(3,2)
print(X5)

tensor([[0.0583, 0.5844],
        [0.5830, 0.9661],
        [0.8054, 0.5592]])


In [6]:
# tensor shapes

X3.shape

torch.Size([3, 2])

In [7]:
i = torch.tensor([10,20,30])
print(i[1])

tensor(20)


In [8]:
l = torch.tensor([[1,2,3],
                  [4,5,6]])
print(l[0,1])
print(l[1,2])

tensor(2)
tensor(6)


In [10]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(a*b)
print(a+b)

print(a*3)
print((a+b)*4)

tensor([ 4, 10, 18])
tensor([5, 7, 9])
tensor([3, 6, 9])
tensor([20, 28, 36])


In [13]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

# creating tensors using numpy

n = torch.from_numpy(arr)
print(n)

[1 2 3]
tensor([1, 2, 3])
